/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectkasirbarokah;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author user
 */
public class GuiTambahStok extends javax.swing.JFrame {

    /**
     * Creates new form GuiTambahStok
     */
    private final String brngQuery = "SELECT nama_barang from barang ORDER BY ID_BARANG ASC";
    private ResultSet rs = new Koneksi().KoneksiMariaDB(brngQuery);
    private final GuiMenuUtama gmu;
    private int stok_barang = 0;
    public GuiTambahStok(GuiMenuUtama gmu) {
        initComponents();
        this.gmu = gmu;
        ArrayList<String> list = new ArrayList();
        try {
            while(rs.next()){
                list.add(rs.getString(1));
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(GuiTambahStok.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBox1.setModel(new DefaultComboBoxModel(list.toArray()));
        jLabel4.setText("-");
        jFormattedTextField1.setEnabled(false);
        AutoCompletion.enable(jComboBox1);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NumberFormat format = NumberFormat.getIntegerInstance();
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setAllowsInvalid(false);
        // If you want the value to be committed on each keystroke instead of focus lost
        formatter.setCommitsOnValidEdit(true);
        jFormattedTextField1 = new javax.swing.JFormattedTextField(formatter);
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tambah Stok");

        jLabel2.setText("Cari Barang");

        jComboBox1.setEditable(true);
        jComboBox1.setFont(jComboBox1.getFont().deriveFont(jComboBox1.getFont().getStyle() & ~java.awt.Font.BOLD, jComboBox1.getFont().getSize()+6));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel3.setText("Stok Saat Ini");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Tambah Stok");

        jLabel5.setText("Berapa banyak?");

        jFormattedTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jFormattedTextField1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        jFormattedTextField1.setEnabled(true);
        ResultSet rsStok = new Koneksi().KoneksiMariaDB("Select stok_barang from barang where id_barang = " + (jComboBox1.getSelectedIndex()+1));
        System.out.println("id_barang = " + (jComboBox1.getSelectedIndex()+1));
        try {
            while(rsStok.next()){
                stok_barang = rsStok.getInt(1);
                System.out.println("Stok_Barang: " + stok_barang);
            }
            rsStok.close();
        } catch (SQLException ex) {
            Logger.getLogger(GuiTambahStok.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel4.setText(String.valueOf(stok_barang));
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jFormattedTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE){
            getToolkit().beep();
            jFormattedTextField1.setValue(null);
            //jLabel8.setText("Rp.");
        } else if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(jFormattedTextField1.getValue()==null){
                getToolkit().beep();
            } else {
                //jButton7.doClick();
                jComboBox1.requestFocus();
            }
        } else {
            //JOptionPane.showMessageDialog(null,"\""+ jFormattedTextField1.getValue() + "\"");
            try{
                if(evt.getKeyChar() == '0' && jFormattedTextField1.getValue() == null){
                    JOptionPane.showMessageDialog(null, "Menambahkan Stok Barang Tidak boleh 0!");
                    jFormattedTextField1.setValue(null);
                }
            } catch (NumberFormatException e){
                getToolkit().beep();
            }
        }
    }//GEN-LAST:event_jFormattedTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jFormattedTextField1.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Tidak Boleh Kosong!");
        } else {
            /*new Koneksi().KoneksiMariaDBDenganIsi("INSERT INTO BARANG_MASUK_DAN_KELUAR(id_barang, tanggal, stok_masuk, stok_keluar) values (?, curdate(), ?, null)", new String[]{
                String.valueOf((jComboBox1.getSelectedIndex()+1)),
                String.valueOf(jFormattedTextField1.getValue())
            });*/
            new Koneksi().KoneksiMariaDBDenganIsi("UPDATE barang"
                    + " SET barang.stok_barang = barang.stok_barang+?"
                    + " WHERE barang.id_barang = ?", new String[]{
                        String.valueOf(jFormattedTextField1.getValue()),
                        String.valueOf(jComboBox1.getSelectedIndex()+1)
                    });
            dispose();
            gmu.updateTableBarang();
            gmu.updateTableBMBK();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
