/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectkasirbarokah;

import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author user
 */
public class GuiUpdatePegawai extends javax.swing.JFrame {

    /**
     * Creates new form GuiUpdatePegawai
     */
    private GuiMenuUtama gmu;
    private boolean cekbox1 = false;
    private ResultSet pnjgResultSet = new KoneksiOracle().KoneksiOracleDB("SELECT * FROM PENJAGA ORDER BY ID_PENJAGA ASC");
    public GuiUpdatePegawai(GuiMenuUtama gmu) {
        initComponents();
        this.gmu = gmu;
        setLocationRelativeTo(null);
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jPasswordField1.setEnabled(false);
        jCheckBox1.setEnabled(false);
        jButton2.setVisible(false);
        jButton1.setEnabled(false);
        ArrayList<String> list = new ArrayList();
        try{
            pnjgResultSet.beforeFirst();
            while(pnjgResultSet.next()){
                list.add(pnjgResultSet.getString(2));
            }
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error while processing data: " + e.getMessage());
        }
        jComboBox1.setModel(new DefaultComboBoxModel(list.toArray()));
        AutoCompletion.enable(jComboBox1);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ubah Info Pegawai");

        jLabel2.setText("Cari Nama Pegawai");

        jComboBox1.setEditable(true);
        jComboBox1.setFont(jComboBox1.getFont().deriveFont(jComboBox1.getFont().getStyle() & ~java.awt.Font.BOLD, jComboBox1.getFont().getSize()+6));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel3.setText("Ubah Nama Pegawai disini: (Jika tidak ingin mengubah nama pegawai, abaikan)");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setText("Ubah username pegawai disini: (Jika tidak ingin mengubah username, abaikan)");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setText("Ubah password pegawai disini: (Jika tidak ingin mengubah password, abaikan)");

        jCheckBox1.setText("Pegawai ini telah keluar dari toko (otomatis akan menambahkan tanggal keluar)");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jButton1.setText("UBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pegawai ini masuk kembali jadi pegawai toko");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED){
            int id_barang = jComboBox1.getSelectedIndex();
            System.out.println("id_barang : " + id_barang);
            String nmString = "";
            String userString = "";
            String passString = "";
            boolean resign = false;
            try{
                pnjgResultSet.beforeFirst();
                while(pnjgResultSet.next()){
                    if(id_barang+1 == pnjgResultSet.getInt(1)){
                        System.out.println("found it!");
                        nmString = pnjgResultSet.getString(2);
                        userString = pnjgResultSet.getString(5);
                        passString = pnjgResultSet.getString(6);
                        if(pnjgResultSet.getDate(4) != null){
                            resign = true;
                        }
                    }
                }
            } catch (SQLException e){
                System.out.println("Error: "+e.getMessage());
            }
            jTextField1.setText(nmString);
            jTextField2.setText(userString);
            jPasswordField1.setText(passString);
            jTextField1.setEnabled(true);
            jTextField2.setEnabled(true);
            jPasswordField1.setEnabled(true);
            jCheckBox1.setEnabled(true);
            jCheckBox1.setSelected(false);
            jButton1.setEnabled(true);
            jButton2.setVisible(false);
            if(resign == true){
                jButton2.setVisible(true);
                jCheckBox1.setSelected(true);
                jTextField1.setEnabled(false);
                jTextField2.setEnabled(false);
                jPasswordField1.setEnabled(false);
                jCheckBox1.setEnabled(false);
                jButton1.setEnabled(false);
            } else {
                
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        int pil = JOptionPane.showConfirmDialog(null, "Apakah anda yakin untuk mengubah data ini?", "Ubah?", JOptionPane.YES_NO_OPTION);
        if(pil == JOptionPane.YES_OPTION){
            String[] isi = {
                jTextField1.getText(),
                jTextField2.getText(),
                String.valueOf(jPasswordField1.getPassword()),
                String.valueOf(jComboBox1.getSelectedIndex()+1)
            };
            if(!cekbox1){
                new KoneksiOracle().KoneksiOracleDBDenganIsi("UPDATE PENJAGA SET nama_penjaga = ?, username = ?, password = ? WHERE ID_PENJAGA = ?", isi);
            } else {
                new KoneksiOracle().KoneksiOracleDBDenganIsi("UPDATE PENJAGA SET tanggal_keluar = (select sysdate from dual) , nama_penjaga = ?, username = ?, password = ? WHERE ID_PENJAGA = ?", isi);
            }
            try{
                pnjgResultSet.close();
            } catch (SQLException e){
                System.err.println("Error: " + e.getMessage());
            }
            gmu.updateTablePenjaga();
            dispose();
        } else if (pil == JOptionPane.NO_OPTION){
            this.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED){
            cekbox1 = true;
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            jPasswordField1.setEnabled(false);
        } else {
            cekbox1 = false;
            jTextField1.setEnabled(true);
            jTextField2.setEnabled(true);
            jPasswordField1.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin mengaktifkan pegawai yang telah berstatus keluar?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if(check == JOptionPane.YES_OPTION){
            String konfirmasi = JOptionPane.showInputDialog(null, "Untuk Konfirmasi, Silahkan masukan NAMA penjaga yang terdaftar pada sistem lengkap dengan huruf kecil dan besar");
            if(konfirmasi.equals(jComboBox1.getSelectedItem())){
                new KoneksiOracle().KoneksiOracleDB("UPDATE penjaga SET tanggal_masuk = (select sysdate from dual), tanggal_keluar = null WHERE id_penjaga = " + (jComboBox1.getSelectedIndex()+1));
                dispose();
                gmu.updateTablePenjaga();
            } else {
                JOptionPane.showMessageDialog(null, "Inputan nama tidak sesuai!, Pengaktifan kembali dibatalkan!");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showUpdatePegawai(GuiMenuUtama gmu) {
        /* Set the Nimbus look and feel */
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e){
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GuiUpdatePegawai(gmu).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
